export const weatherCodeMap: {
    [code: number]: { label: string; icon: string; borderColor: string };
} = {
    0: { label: "Clear sky", icon: "wi:day-sunny", borderColor: "#FFD700" },
    1: { label: "Mainly clear", icon: "wi:day-sunny-overcast", borderColor: "#FFE066" },
    2: { label: "Partly cloudy", icon: "wi:day-cloudy", borderColor: "#B0C4DE" },
    3: { label: "Overcast", icon: "wi:cloudy", borderColor: "#A9A9A9" },
    45: { label: "Fog", icon: "wi:fog", borderColor: "#C0C0C0" },
    48: { label: "Depositing rime fog", icon: "wi:fog", borderColor: "#E0E0E0" },
    51: { label: "Light drizzle", icon: "wi:sprinkle", borderColor: "#ADD8E6" },
    53: { label: "Moderate drizzle", icon: "wi:showers", borderColor: "#87CEEB" },
    55: { label: "Dense drizzle", icon: "wi:rain", borderColor: "#4682B4" },
    56: { label: "Light freezing drizzle", icon: "wi:rain-mix", borderColor: "#B0E0E6" },
    57: { label: "Dense freezing drizzle", icon: "wi:sleet", borderColor: "#AFEEEE" },
    61: { label: "Slight rain", icon: "wi:raindrops", borderColor: "#00BFFF" },
    63: { label: "Moderate rain", icon: "wi:rain", borderColor: "#1E90FF" },
    65: { label: "Heavy rain", icon: "wi:rain-wind", borderColor: "#4169E1" },
    66: { label: "Light freezing rain", icon: "wi:rain-mix", borderColor: "#B0E0E6" },
    67: { label: "Heavy freezing rain", icon: "wi:rain-mix", borderColor: "#4682B4" },
    71: { label: "Slight snow fall", icon: "wi:snow", borderColor: "#F0F8FF" },
    73: { label: "Moderate snow fall", icon: "wi:snowflake-cold", borderColor: "#E0FFFF" },
    75: { label: "Heavy snow fall", icon: "wi:snow-wind", borderColor: "#B0C4DE" },
    77: { label: "Snow grains", icon: "wi:snow", borderColor: "#F8F8FF" },
    80: { label: "Slight rain showers", icon: "wi:showers", borderColor: "#87CEEB" },
    81: { label: "Moderate rain showers", icon: "wi:rain", borderColor: "#4682B4" },
    82: { label: "Violent rain showers", icon: "wi:storm-showers", borderColor: "#191970" },
    85: { label: "Slight snow showers", icon: "wi:snow", borderColor: "#E0FFFF" },
    86: { label: "Heavy snow showers", icon: "wi:snow-wind", borderColor: "#B0C4DE" },
    95: { label: "Thunderstorm", icon: "wi:thunderstorm", borderColor: "#FFA500" },
    96: { label: "Thunderstorm with slight hail", icon: "wi:storm-showers", borderColor: "#FF8C00" },
    99: { label: "Thunderstorm with heavy hail", icon: "wi:thunderstorm", borderColor: "#8B0000" },
};